spring:
  datasource:
    password: Zy1314521..
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.212.202:3306/omdb?useUnicode=true&characterEncoding=utf-8
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
#    url: jdbc:mysql://localhost:3306/omdb
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
